version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "bradp"
    versioning-strategy: increase
    groups:
      dev-dependencies:
        applies-to: version-updates
        patterns:
          - "*"
